### PR TITLE
Update documentation for Symfony 2.x compatibility

### LINKED ISSUE #23: Update installation insctructions
Installation instructions needs an update to work with my app using Symfony 2.8.8.
The file M6WebDaemonBundle.php required by my AppKernel is appears only since V 1.2.0.

## Installation (that works for me)

Via composer :

```json
"require": {
    "m6web/daemon-bundle":"1.4.*"
}
```

then enable the bundle in your kernel:

```php
<?php

$bundles = [
    new M6Web\Bundle\DaemonBundle\M6WebDaemonBundle()
];
```

### PR DESCRIPTION
**Pull request by Oliboy50**
Update documentation for Symfony <3.0
+ fixes #23

### CODE REVIEW

**Comment by lnahiro** [comment]
:+1:

**Comment by NastasiaSaby** [comment]
:+1:

**Comment by gbouyge** [comment]
👍

**Comment by omansour** [comment]
see #22 on passe en v3 ..

**Comment by Oliboy50** [comment]
@omansour updated

**Pull request merged**
