### PR TITLE
Correctly reading iterations_events configuration

### PR DESCRIPTION
**Pull request by mguillermin**

### CODE REVIEW

**Comment by mikaelrandy** [comment]
When i see this fix, i ask myself "how it could work ?"

@fabdsp, what do you think about that ?

**Comment by mguillermin** [comment]
@mikaelrandy well, it didn't (and couldn't) work, that's why I've submitted this PR ;)

**Comment by mguillermin** [comment]
Looking at the log, I would say that it worked only before this commit : https://github.com/M6Web/DaemonBundle/commit/3b76c41d260bb40af955739fdfab1ae61294fc5e

**Comment by t-geindre** [comment]
Never commit directly on master, always open a PR.
I'll remember it :smile:

**Comment by omansour** [comment]
:+1:

**Comment by mikaelrandy** [comment]
:+1:

**Comment by omansour** [comment]
@mguillermin peux tu ajouter dans le commentaire de la PR le tag que tu fait suite à cette PR ? 

merci

**Comment by mguillermin** [comment]
v1.3.1

**Pull request merged**
