### PR TITLE
Chore/compatibilty symfo7

### LINKED ISSUE #40: Update for Symfony 7.x
Hello,

I was trying to update my app to Symfony 7.x.
After a "**composer update -W**" with all Symfony dependencies targeted to ^7.0, I had some composer conflicts :

```
Problem 1
  - m6web/daemon-bundle v7.0.0 requires symfony/console ~6.1 -> found symfony/console[v6.1.0, ..., v6.4.4] but it conflicts with your root composer.json require (^7.0).
  - mfy/daemon-command[4.0.0, ..., 4.0.2] require m6web/daemon-bundle ^7.0 -> satisfiable by m6web/daemon-bundle[v7.0.0].
  - Root composer.json requires mfy/daemon-command ^4.0 -> satisfiable by mfy/daemon-command[4.0.0, 4.0.1, 4.0.2].
```

Is it planned to update DaemonBundle for Symfony 7.x ?

Thanks!

### PR DESCRIPTION
**Pull request by pforesi**
Fixing deprecation to upgrade to symfony 7
Minor changes on php typing compatibilty (set minimal php version to 8.2)
Fixes #40

### CODE REVIEW

**Review by Oliboy50 — APPROVED** [review]
thank you for the PR

IMO it seems like a big breaking change to drop support for Symfony 6.x which is a pretty recent and still supported Symfony release, could you try to support both `~6.1` and `~7.0`? (you can use the `ci.yml` GHA workflow to assert that it still works fine using both `6.1` and `7.0` versions)

**Comment by pforesi** [comment]
@Oliboy50 adding back compatibilty for sf6.

**Comment by Oliboy50** [comment]
@pforesi thank you, I fixed the trigger of the CI on the default branch

now in order for your branch to be tested against the CI, could you please rebase your branch on top of `master` please?

**Review by Oliboy50 — APPROVED** [review]
💯

**Comment by pforesi** [comment]
@Oliboy50 everything ok ?

**Review by t-geindre — APPROVED** [review]

**Comment by Oliboy50** [comment]
thanks https://packagist.org/packages/m6web/daemon-bundle#v8.0.0

**Comment by pforesi** [comment]
Thnaks for your quick support :)

**Pull request merged**
